name:                congruencer
version:             0.1.0.0
github:              "pmalex/congruencer"
license:             BSD3
author:              "Pryanichnikov Alexey"
maintainer:          "genary@ya.ru"
copyright:           "2019 Pryanichnikov Alexey"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Abstract Algebra

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pmalex/congruencer#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  congruencer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - congruencer

tests:
  congruencer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - congruencer
    - hspec
    - QuickCheck
